### ISSUE TITLE
Проблемы, связанные со светлой/темной темой

### ISSUE THREAD

**Issue by artemgur** [queuejw/Neko11#7]
Привет)
Отличное приложение, случайно наткнулся на него на днях.
Но столкнулся с некоторыми проблемами, связанными со светлой/темной темой.
Телефон – Google Pixel 6a, Android 14
1. "Автоматическая темная тема" не всегда работает.
2. Если "Включить темную тему" отключено, то "Автоматическая темная тема" нельзя отключить. То есть, если отключить "Автоматическая темная тема", выйти из настроек и зайти обратно, эта настройка снова будет включена.
3. Если, когда на устройстве темная тема, попереключать рандомно переключатели "Включить темную тему" и "Автоматическая темная тема", возникает следующий Exception:
```
Detected critical error.
 Model: Pixel 6a
Brand: google
Neko11 Ver: 2.3_12_04
java.lang.IllegalStateException: Fragment w{fda3df6} (35103270-3ec9-43a7-94c2-865920f475a4) not attached to a context.
 at androidx.fragment.app.D.M(SourceFile:18)
 at androidx.fragment.app.D.l(SourceFile:1)
 at androidx.fragment.app.D.n(SourceFile:1)
 at e.t.run(SourceFile:54)
 at android.os.Handler.handleCallback(Handler.java:959)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loopOnce(Looper.java:232)
 at android.os.Looper.loop(Looper.java:317)
 at android.app.ActivityThread.main(ActivityThread.java:8501)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```
(16-ричные строки в строчке с java.lang.IllegalStateException каждый раз разные)
В какой конкретно последовательности нужно переключать эти переключатели, непонятно. Но если просто рандомно попереключать их, ошибка стабильно воспроизводится, и достаточно быстро.
4. В целом, если по-разному попереключать эти переключатели, иногда приложение ведет себя странно. Это проявляется по-разному и не всегда (в том числе, зависит от того, светлая или темная тема на телефоне)

**Comment by artemgur** [comment]
Да, все отлично, спасибо)
